name: Linter

# Triggers the workflow on push or pull request
# events on all branches
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Super-Linter
      uses: github/super-linter@v3.3.2
